default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_ninja_development

test:
  <<: *default
  database: budget_ninja_test

production:
  <<: *default
  database: budget_ninja_production
